JWT + Validators problems fixed
franGiangiordano/TTADS-Backend pull request #2
Opened 2023-09-25 00:23 UTC by gturconi

- Se arreglaron los validadores de Chofer y Usuario (todos los campos eran requeridos al hacer una modificación)
- Se agregó una tabla de Roles para los usuarios (cada usuario puede tener uno o más roles)
- Se implementó JWT y se añadieron middlewares a las rutas para validar permisos
- Se modificó el ABM de Usuario para adaptarlo al nuevo sistema
- Faltaría hacer el logout

Revisen el código y cualquier cosa me van diciendo
Lo estuve testeando y respondió bien, de todas maneras me gustaría que lo prueben para estar seguros
Para hacer peticiones POST, PUT o DELETE, incluir el token mediante la cabecera: "x-access-token".

2023-09-25 22:13 UTC, MartinLambrecht requested changes
Más que nada el formateo y el estilo del codigó, de funcionalidad lo veo bien. Cuando este mergeado le aplico un poco de clean code para tipar algunas cosas y extraer otras que se repiten.

2023-09-25 22:13 UTC, MartinLambrecht commented on src/controllers/auth.ts
> +
Espacio

2023-09-25 22:13 UTC, MartinLambrecht commented on src/controllers/auth.ts
> +  } catch (error) {
Se podria tipar el error

2023-09-25 22:13 UTC, MartinLambrecht commented on src/controllers/auth.ts
> +    console.log(error);
Quedo un console log colgado acá

2023-09-25 22:13 UTC, MartinLambrecht commented on src/controllers/auth.ts
> +      expiresIn: 86400,
Estaria bueno pasarlo a una constante en otro archivo

2023-09-25 22:13 UTC, MartinLambrecht commented on src/controllers/auth.ts
> +    newUser.password = await User.encryptPassword(newUser.password);
Esta encriptando la contraseña en el back o entiendo mal? Se debería recibir directamente encriptada

2023-09-25 22:13 UTC, MartinLambrecht commented on src/controllers/batea.ts
> +      return res.status(500).json({message: 'No se pudo editar la batea'});
Todo el codigo del catch se repite en los distintos ABM, podriamos ver de extraerlo a que tire un 500 genérico y no tener que catchear con cada interaccion a la DB (Esto lo hacemos en un refactor después de que se mergee, solo lo pongo para que sepas 😄 )

2023-09-25 22:13 UTC, MartinLambrecht commented on src/routes/user.ts
> +//router.post("/", validatorUser, createUser);
Quedo un comment acá

2023-09-25 22:19 UTC, MartinLambrecht commented on src/controllers/auth.ts
> +    newUser.password = await User.encryptPassword(newUser.password);
O hacer una doble encriptacion, pero no deberia viajar la contraseña plana del front al back

2023-09-26 20:05 UTC, gturconi commented on src/controllers/auth.ts
> +    newUser.password = await User.encryptPassword(newUser.password);
No se si deberíamos encriptar la contraseña en el cliente porque todo el mundo va a poder ver el código fuente y averiguar como encriptas. Lo usual sería que la contraseña viaje al servidor por HTTPS y encriptarla en el back. Aunque la opción de doble encriptación tampoco está mal, podríamos hacer eso.

2023-09-26 20:12 UTC, gturconi commented on src/controllers/batea.ts
> +      return res.status(500).json({message: 'No se pudo editar la batea'});
Joya, estaría bueno 😁

2023-10-24 20:35 UTC, merged